pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        // Essential for Kotlin/Wasm to find Node.js
        ivy {
            url = "https://nodejs.org/dist"
            patternLayout {
                artifact("v[revision]/[artifact]-[revision]-[classifier].[ext]")
            }
            metadataSources {
                artifact()
            }
        }
    }
}
rootProject.name = "CleaningChoresProject"
include ':app'
