package com.example.myapp.ui

object AppStrings {
    const val app_name = "לוח תורנויות"
    const val add_person_title = "הוספת משתתף חדש 👤"
    const val edit_person_title = "עריכת משתתף"
    const val person_name_hint = "שם המשתתף"
    const val gender_label = "מגדר"
    const val gender_male = "בן"
    const val gender_female = "בת"
    const val add_button = "הוסף לרשימה"
    const val generate_button = "🎲 הגרל סידור שבועי חדש"
    const val people_list_title = "רשימת משתתפים"
    const val availability_hint = "ימי היעדרות (לא זמין)"
    const val save_button = "שמור"
    const val lottery_button = "🎲 הגרל"
    const val nav_schedule = "לוח"
    const val nav_stats = "סטטיסטיקה"
    const val nav_settings = "הגדרות"
    const val no_schedule_title = "אין סידור כרגע 📅"
    const val no_schedule_subtitle = "הגרל שבוע חדש בהגדרות"
    const val day_prefix = "יום %s"
    const val edit_assignment = "ערוך"
    const val save_assignment = "שמור"
    const val share_whatsapp = "שתף סידור שבועי ל-WhatsApp 📱"
    const val add_person_fab = "משתתף"
    const val add_chore_fab = "משימה"
    const val priority_label = "עדיפות:"
    const val add_chore_title = "הוספת משימה חדשה 🧹"
    const val chore_name_hint = "שם המשימה"
    const val save_chore = "שמור משימה"
    
    const val stats_title = "חלוקת עומסים"
    const val stats_subtitle = "מי עובד הכי קשה השבוע?"
    const val stats_no_data = "אין מספיק נתונים להצגת גרף"
    const val stats_how_title = "איך זה מחושב?"
    const val stats_how_desc = "כל משימה מקבלת ניקוד לפי רמת הקושי שלה: קשה (3), בינוני (2), קל (1). הגרף מראה את אחוז הניקוד המצטבר של כל תורן מתוך כלל המשימות שחולקו השבוע."
    
    const val chores_title = "משימות"
    const val chores_subtitle = "הגדר אילו משימות לבצע ומה העדיפות שלהן"
    const val add_chore_button = "הוסף משימה"
    const val use_priorities_label = "השתמש בעדיפויות משימה"
    const val use_priorities_desc = "כאשר כבוי, כל המשימות ייחשבו שוות בחלוקת העומסים ובהגרלה"
    const val manage_people_subtitle = "נהל את רשימת התורנים"
    const val empty_people_msg = "רשימה ריקה. הוסף אנשים כדי להתחיל."
}
